# ip
renting.ip=127.0.0.1
# eureka
eureka.port=16000
eureka.server.url=http://127.0.0.1:16000/eureka/
# uaa
uaa.port=16010
# service
account.port=16100
user.port=16200
place.port=16808
housing.port=16300
im.port=16400
# gateway
gateway.port=17000
# redis
redis.server.url=127.0.0.1
redis.server.port=6379
# mongodb
mongodb.server.url=127.0.0.1
mongodb.server.port=27017
